---
title: "Actin_Modeling_Prelab"
author: "Keegan Ballantyne"
date: "4/13/2021"
output: html_document

```{r}
# Part I
rm(list=ls())
# Read in CSV File
profilin <- read.csv("/Users/keeganballantyne/Documents/CSV Files/Profilin_AssemblyCurves.csv")

time <- profilin$Time
actin <- profilin$ActinOnly
p0.5 <- profilin$p0_5uM
p1 <- profilin$p1uM
p2 <- profilin$p2uM
p3 <- profilin$p3uM
p4 <- profilin$p4uM
p5 <- profilin$p5uM
p7.5 <- profilin$p7_5uM
p10 <- profilin$p10uM
p12.5 <- profilin$p12_5uM
p15 <- profilin$p15uM

cl <- rainbow(11)

plot(time, actin, type = "l", xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curves", col = cl[1])
lines(time, p0.5, col = cl[2])
lines(time, p1, col = cl[3])
lines(time, p2, col = cl[4])
lines(time, p3, col = cl[5])
lines(time, p4, col = cl[6])
lines(time, p5, col = cl[7])
lines(time, p7.5, col = cl[8])
lines(time, p10, col = cl[9])
lines(time, p12.5, col = cl[10])
lines(time, p15, col = cl[11])

legend("topleft", legend = c("actin only 2.5uM","p0.5uM","p1uM","p2uM","p3uM", "p4uM","p5uM","p7.5uM","p10uM","p12.5uM","p15uM"), col = cl, lty = 1, cex = 0.5)

# I see that all of the curves have a positive slope but each curve has a different steep of a slope. Actin only with a 2.5uM concentration has the steepest slope whereas profilin at 10uM has the least steepest curve. It appears that as you increase the concentration of profilin the slope of the curve gets less and less steeper. This shows that the assembly of actin decreases as you increase profilin concentration and decreases the fluoresence on shown on the graph. The only curves that go outside this trend is the profilin concentrations 7.5uM, 12.5uM, and 15uM because the 7.5uM is above curves with profilin concentrations of 2-5uM and 12.5uM and 15uM is above the curve with procilin contration of 10uM.

```

```{r}
# Part II

plot(time[50:90], actin[50:90], type = "l", xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curves", col = cl[1], ylim = c(195, 350))
lines(time[50:90], p0.5[50:90], col = cl[2])
lines(time[50:90], p1[50:90], col = cl[3])
lines(time[50:90], p2[50:90], col = cl[4])
lines(time[50:90], p3[50:90], col = cl[5])
lines(time[50:90], p4[50:90], col = cl[6])
lines(time[50:90], p5[50:90], col = cl[7])
lines(time[50:90], p7.5[50:90], col = cl[8])
lines(time[50:90], p10[50:90], col = cl[9])
lines(time[50:90], p12.5[50:90], col = cl[10])
lines(time[50:90], p15[50:90], col = cl[11])

legend("topleft", legend = c("actin only 2.5uM","p0.5uM","p1uM","p2uM","p3uM", "p4uM","p5uM","p7.5uM","p10uM","p12.5uM","p15uM"), col = cl, lty = 1, cex = 0.34)

# In this specific time section we see a similar trend that we see in the previous graph. These curves all have slightly positive slopes, where the curve with the steepest slope is the actin only at 2.5uM and the curve with the least steepest slope is the profilin 10uM. This graph also supports the claim that as you increase the concentration of profilin it decreases the assembly of actin and decreases fluoresence shown on the graph. Again, only curves that go outside this trend is the profilin concentrations 7.5uM, 12.5uM, and 15uM because the 7.5uM is above curves with profilin concentrations of 2-5uM and 12.5uM and 15uM is above the curve with procilin contration of 10uM.

```

```{r}
#Part III
#actinonly
actinonlyfit <- lm(actin[50:90]~time[50:90]) #(lm=linear model), y = variable on y axis, x = variable of x axis

actinintercept <- actinonlyfit$coefficients[1]
actinslope <- actinonlyfit$coefficients[2]
actinR2 <- summary(actinonlyfit)$r.squared

plot(time[50:90], actin[50:90], xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curve Actin Only 2.5uM", col = cl[1], ylim = c(195, 350))
abline(actinonlyfit)
legend("topleft", bty="n", legend=paste("R2 is", format(summary(actinonlyfit)$r.squared, digits=4)),)

profilin_slope <- vector()
profilin_slope[1] <- actinslope
#p0.5uM
p0.5fit <- lm(p0.5[50:90]~time[50:90]) #(lm=linear model), y = variable on y axis, x = variable of x axis

p0.5intercept <- p0.5fit$coefficients[1]
p0.5slope <- p0.5fit$coefficients[2]
p0.5R2 <- summary(p0.5fit)$r.squared

plot(time[50:90], p0.5[50:90], xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curve 0.5uM", col = cl[1], ylim = c(195, 350))
abline(p0.5fit)
legend("topleft", bty="n", legend=paste("R2 is", format(summary(p0.5fit)$r.squared, digits=4)),)

profilin_slope <- vector()
profilin_slope[2] <- p0.5slope
#p1uM
p1fit <- lm(p1[50:90]~time[50:90]) #(lm=linear model), y = variable on y axis, x = variable of x axis

p1intercept <- p1fit$coefficients[1]
p1slope <- p1fit$coefficients[2]
p1R2 <- summary(p1fit)$r.squared

plot(time[50:90], p1[50:90], xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curve 1uM", col = cl[1], ylim = c(195, 350))
abline(p1fit)
legend("topleft", bty="n", legend=paste("R2 is", format(summary(p1fit)$r.squared, digits=4)),)

profilin_slope <- vector()
profilin_slope[3] <- p1slope
#p2uM
p2fit <- lm(p2[50:90]~time[50:90]) #(lm=linear model), y = variable on y axis, x = variable of x axis

p2intercept <- p2fit$coefficients[1]
p2slope <- p2fit$coefficients[2]
p2R2 <- summary(p2fit)$r.squared

plot(time[50:90], p2[50:90], xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curve 2uM", col = cl[1], ylim = c(195, 350))
abline(p2fit)
legend("topleft", bty="n", legend=paste("R2 is", format(summary(p2fit)$r.squared, digits=4)),)

profilin_slope <- vector()
profilin_slope[4] <- p2slope
#p3
p3fit <- lm(p3[50:90]~time[50:90]) #(lm=linear model), y = variable on y axis, x = variable of x axis

p3intercept <- p3fit$coefficients[1]
p3slope <- p3fit$coefficients[2]
p3R2 <- summary(p3fit)$r.squared

plot(time[50:90], p3[50:90], xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curve 3uM", col = cl[1], ylim = c(195, 350))
abline(p3fit)
legend("topleft", bty="n", legend=paste("R2 is", format(summary(p3fit)$r.squared, digits=4)),)

profilin_slope <- vector()
profilin_slope[4] <- p3slope








```

```{r}
#Part IV









```

```{r}
#Part V







```