---
title: "Binding Affinity Lab"
author: "Keegan Ballantyne"
date: "4/20/2021"
output: html_document
---
```{r}
# Part I
rm(list=ls())
# Read in CSV File
profilin <- read.csv("/Users/keeganballantyne/Documents/CSV Files/Profilin_AssemblyCurves.csv")

time <- profilin$Time
actin <- profilin$ActinOnly
p0.5 <- profilin$p0_5uM
p1 <- profilin$p1uM
p2 <- profilin$p2uM
p3 <- profilin$p3uM
p4 <- profilin$p4uM
p5 <- profilin$p5uM
p7.5 <- profilin$p7_5uM
p10 <- profilin$p10uM
p12.5 <- profilin$p12_5uM
p15 <- profilin$p15uM

cl <- rainbow(11)

plot(time, actin, type = "l", xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curves", col = cl[1])
lines(time, p0.5, col = cl[2])
lines(time, p1, col = cl[3])
lines(time, p2, col = cl[4])
lines(time, p3, col = cl[5])
lines(time, p4, col = cl[6])
lines(time, p5, col = cl[7])
lines(time, p7.5, col = cl[8])
lines(time, p10, col = cl[9])
lines(time, p12.5, col = cl[10])
lines(time, p15, col = cl[11])

legend("topleft", legend = c("actin only 2.5uM","p0.5uM","p1uM","p2uM","p3uM", "p4uM","p5uM","p7.5uM","p10uM","p12.5uM","p15uM"), col = cl, lty = 1, cex = 0.5)

# I see that all of the curves have a positive slope but each curve has a different steep of a slope. Actin only with a 2.5uM concentration has the steepest slope whereas profilin at 10uM has the least steepest curve. It appears that as you increase the concentration of profilin the slope of the curve gets less and less steeper. This shows that the assembly of actin decreases as you increase profilin concentration and decreases the fluoresence on shown on the graph. The only curves that go outside this trend is the profilin concentrations 7.5uM, 12.5uM, and 15uM because the 7.5uM is above curves with profilin concentrations of 2-5uM and 12.5uM and 15uM is above the curve with procilin contration of 10uM.

```

```{r}
# Part II

plot(time[50:90], actin[50:90], type = "l", xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curves", col = cl[1], ylim = c(195, 350))
lines(time[50:90], p0.5[50:90], col = cl[2])
lines(time[50:90], p1[50:90], col = cl[3])
lines(time[50:90], p2[50:90], col = cl[4])
lines(time[50:90], p3[50:90], col = cl[5])
lines(time[50:90], p4[50:90], col = cl[6])
lines(time[50:90], p5[50:90], col = cl[7])
lines(time[50:90], p7.5[50:90], col = cl[8])
lines(time[50:90], p10[50:90], col = cl[9])
lines(time[50:90], p12.5[50:90], col = cl[10])
lines(time[50:90], p15[50:90], col = cl[11])

legend("topleft", legend = c("actin only 2.5uM","p0.5uM","p1uM","p2uM","p3uM", "p4uM","p5uM","p7.5uM","p10uM","p12.5uM","p15uM"), col = cl, lty = 1, cex = 0.34)

# In this specific time section we see a similar trend that we see in the previous graph. These curves all have slightly positive slopes, where the curve with the steepest slope is the actin only at 2.5uM and the curve with the least steepest slope is the profilin 10uM. This graph also supports the claim that as you increase the concentration of profilin it decreases the assembly of actin and decreases fluoresence shown on the graph. Again, only curves that go outside this trend is the profilin concentrations 7.5uM, 12.5uM, and 15uM because the 7.5uM is above curves with profilin concentrations of 2-5uM and 12.5uM and 15uM is above the curve with procilin contration of 10uM.

```

```{r}
#Part III

#actinonly
actinonlyfit <- lm(actin[50:90]~time[50:90]) #(lm=linear model), y = variable on y axis, x = variable of x axis

actinintercept <- actinonlyfit$coefficients[1]
actinslope <- actinonlyfit$coefficients[2]
actinR2 <- summary(actinonlyfit)$r.squared

plot(time[50:90], actin[50:90], xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curve Actin Only 2.5uM", col = cl[1], ylim = c(195, 350))
abline(actinonlyfit)
legend("topleft", bty="n", legend=paste("R2 is", format(summary(actinonlyfit)$r.squared, digits=4)),)

profilin_slope <- vector()
profilin_slope[1] <- actinslope

#This R2 is very high (it's more than 0.95) compared to the rest of the curves, so this indicates that this model does fit the profilin data extremely well.

#p0.5uM
p0.5fit <- lm(p0.5[50:90]~time[50:90]) #(lm=linear model), y = variable on y axis, x = variable of x axis

p0.5intercept <- p0.5fit$coefficients[1]
p0.5slope <- p0.5fit$coefficients[2]
p0.5R2 <- summary(p0.5fit)$r.squared

plot(time[50:90], p0.5[50:90], xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curve 0.5uM", col = cl[1], ylim = c(195, 350))
abline(p0.5fit)
legend("topleft", bty="n", legend=paste("R2 is", format(summary(p0.5fit)$r.squared, digits=4)),)

profilin_slope[2] <- p0.5slope

#This R2 is pretty high (it's more than 0.90) compared to the rest of the curves, so this indicates that this model does fit the profilin data pretty well.

#p1uM
p1fit <- lm(p1[50:90]~time[50:90]) #(lm=linear model), y = variable on y axis, x = variable of x axis

p1intercept <- p1fit$coefficients[1]
p1slope <- p1fit$coefficients[2]
p1R2 <- summary(p1fit)$r.squared

plot(time[50:90], p1[50:90], xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curve 1uM", col = cl[1], ylim = c(195, 350))
abline(p1fit)
legend("topleft", bty="n", legend=paste("R2 is", format(summary(p1fit)$r.squared, digits=4)),)

profilin_slope[3] <- p1slope

#This R2 is a little bit low (it's less than 0.75 but more than 0.69) compared to the rest of the curves, so this indicates that this model fits the profilin data not super well but not terribly either.

#p2uM
p2fit <- lm(p2[50:90]~time[50:90]) #(lm=linear model), y = variable on y axis, x = variable of x axis

p2intercept <- p2fit$coefficients[1]
p2slope <- p2fit$coefficients[2]
p2R2 <- summary(p2fit)$r.squared

plot(time[50:90], p2[50:90], xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curve 2uM", col = cl[1], ylim = c(195, 350))
abline(p2fit)
legend("topleft", bty="n", legend=paste("R2 is", format(summary(p2fit)$r.squared, digits=4)),)

profilin_slope[4] <- p2slope

#This R2 is low (it's less than 0.75) compared to the rest of the curves, so this indicates that this model doesn't fit the profilin data very well.

#p3
p3fit <- lm(p3[50:90]~time[50:90]) #(lm=linear model), y = variable on y axis, x = variable of x axis

p3intercept <- p3fit$coefficients[1]
p3slope <- p3fit$coefficients[2]
p3R2 <- summary(p3fit)$r.squared

plot(time[50:90], p3[50:90], xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curve 3uM", col = cl[1], ylim = c(195, 350))
abline(p3fit)
legend("topleft", bty="n", legend=paste("R2 is", format(summary(p3fit)$r.squared, digits=4)),)

profilin_slope[5] <- p3slope

#This R2 is pretty high (it's more than 0.75) compared to the rest of the curves, so this indicates that this model does fit the profilin data pretty well.

#p4

p4fit <- lm(p4[50:90]~time[50:90]) #(lm=linear model), y = variable on y axis, x = variable of x axis

p4intercept <- p4fit$coefficients[1]
p4slope <- p4fit$coefficients[2]
p4R2 <- summary(p4fit)$r.squared

plot(time[50:90], p4[50:90], xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curve 4uM", col = cl[1], ylim = c(195, 350))
abline(p4fit)
legend("topleft", bty="n", legend=paste("R2 is", format(summary(p4fit)$r.squared, digits=4)),)

profilin_slope[6] <- p4slope

#This R2 is a little bit low (it's less than 0.75 but more than 0.70) compared to the rest of the curves, so this indicates that this model fits the profilin data not super well but not terribly either.

#p5

p5fit <- lm(p5[50:90]~time[50:90]) #(lm=linear model), y = variable on y axis, x = variable of x axis

p5intercept <- p5fit$coefficients[1]
p5slope <- p5fit$coefficients[2]
p5R2 <- summary(p5fit)$r.squared

plot(time[50:90], p5[50:90], xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curve 5uM", col = cl[1], ylim = c(195, 350))
abline(p5fit)
legend("topleft", bty="n", legend=paste("R2 is", format(summary(p5fit)$r.squared, digits=4)),)

profilin_slope[7] <- p5slope

#This R2 is low (it's less than 0.75) compared to the rest of the curves, so this indicates that this model doesn't fit the profilin data very well.

#p7.5

p7.5fit <- lm(p7.5[50:90]~time[50:90]) #(lm=linear model), y = variable on y axis, x = variable of x axis

p7.5intercept <- p7.5fit$coefficients[1]
p7.5slope <- p7.5fit$coefficients[2]
p7.5R2 <- summary(p7.5fit)$r.squared

plot(time[50:90], p7.5[50:90], xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curve 7.5uM", col = cl[1], ylim = c(195, 350))
abline(p7.5fit)
legend("topleft", bty="n", legend=paste("R2 is", format(summary(p7.5fit)$r.squared, digits=4)),)

profilin_slope[8] <- p7.5slope

#This R2 is pretty high (it's more than 0.75) compared to the rest of the curves, so this indicates that this model does fit the profilin data pretty well.

#p10

p10fit <- lm(p10[50:90]~time[50:90]) #(lm=linear model), y = variable on y axis, x = variable of x axis

p10intercept <- p10fit$coefficients[1]
p10slope <- p10fit$coefficients[2]
p10R2 <- summary(p10fit)$r.squared

plot(time[50:90], p10[50:90], xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curve 10uM", col = cl[1], ylim = c(195, 350))
abline(p10fit)
legend("topleft", bty="n", legend=paste("R2 is", format(summary(p10fit)$r.squared, digits=4)),)

profilin_slope[9] <- p10slope

#This R2 is pretty low (it's less than 0.5) compared to the rest of the curves, so this indicates that this model doesn't fit the profilin data very well.

#p12.5

p12.5fit <- lm(p12.5[50:90]~time[50:90]) #(lm=linear model), y = variable on y axis, x = variable of x axis

p12.5intercept <- p12.5fit$coefficients[1]
p12.5slope <- p12.5fit$coefficients[2]
p12.5R2 <- summary(p12.5fit)$r.squared

plot(time[50:90], p12.5[50:90], xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curve 12.5uM", col = cl[1], ylim = c(195, 350))
abline(p12.5fit)
legend("topleft", bty="n", legend=paste("R2 is", format(summary(p12.5fit)$r.squared, digits=4)),)

profilin_slope[10] <- p12.5slope

#This R2 is the lowest out of all the curves (it's less than 0.25), so this indicates that this model doesn't fit the profilin data very well.

#p15

p15fit <- lm(p15[50:90]~time[50:90]) #(lm=linear model), y = variable on y axis, x = variable of x axis

p15intercept <- p15fit$coefficients[1]
p15slope <- p15fit$coefficients[2]
p15R2 <- summary(p15fit)$r.squared

plot(time[50:90], p15[50:90], xlab = "time (s)", ylab = "fluorescence (arbitrary units)", main = "Profilin Curve 15uM", col = cl[1], ylim = c(195, 350))
abline(p15fit)
legend("topleft", bty="n", legend=paste("R2 is", format(summary(p15fit)$r.squared, digits=4)),)

profilin_slope[11] <- p15slope

#This R2 is pretty low (it's less than 0.5) compared to the rest of the curves, so this indicates that this model doesn't fit the profilin data very well.

```

```{r}
#Part IV

#Profilin Concentrations

profilin_concentrations <- c(0, 0.5, 1, 2, 3, 4, 5, 7.5, 10, 12.5, 15)

plot(profilin_concentrations, profilin_slope, main = "Assembly Rates vs. Profilin Concentrations", xlab = "Profilin Concentration", ylab = "Assembly Rates")

#The curve does not look linear, it looks like an exponentional decaying curve.

kdfit <- nls(profilin_slope ~ (max(profilin_slope)+(min(profilin_slope)-max(profilin_slope))*(((kd+2.5+profilin_concentrations)-sqrt((kd+2.5+profilin_concentrations)^2-4*2.5*profilin_concentrations))/(2*2.5))), start = list(kd = 1))

p <- coef(summary(kdfit))
kd_est <- p[1]
goodfit <- cor(profilin_slope, predict(kdfit))

plot(profilin_concentrations, profilin_slope, main = "Assembly Rates vs. Profilin Concentrations", xlab = "Profilin Concentration", ylab = "Assembly Rates")
lines(profilin_concentrations, predict(kdfit), col = "red")
legend("topright", bty = "n", legend = paste("Kd is", format(kd_est, digits = 4)))
legend("topright", bty = "n", inset = 0.1, legend = paste("Fit is", format(goodfit, digits = 4)))

#The Kd is 0.4768. This is a pretty good fit because it is more than 0.90 so this means that the data fits with the model pretty well.

#The affinity of profilin for g-actin is strong. This means that when you introduce more and more profilin inside the cell, this will further increase the inhibition of actin assembly. 
```

```{r}
#Part V

#Question 5
actin1 <- 100
profilin1 <- 100
kd1 <- 0.4768
sum_apk <- sum(actin1+profilin1+kd1)

AP <- (((sum_apk)-sqrt(((sum_apk)^2)-(4*(actin1*profilin1))))/2)
cat ("The AP value is ")
print(AP)

cat ("The percentage of G-actin that is bound with profilin out of the total actin is ")
print((AP/actin1)*100)

#This means that there will be low actin assembly because most of the g-actin is inhibited by the profilin.

#Question 6

actin2 <- 50
profilin1 <- 100
kd1 <- 0.4768
sum_apk <- sum(actin2+profilin1+kd1)

AP2 <- (((sum_apk)-sqrt(((sum_apk)^2)-(4*(actin2*profilin1))))/2)
cat ("The AP value is ")
print(AP2)

cat ("The percentage of G-actin that is bound with profilin out of the total actin is ")
print((AP2/actin2)*100)

#This means that there will be very little actin assembly because most of the g-actin is inhibited by the profilin.

```
